# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precedence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by default the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
management:
  security:
    enabled: "false"

saml:
  keyStoreFile: "${SAML_KS_FILE}"
  keyStorePassword: "${SAML_KS_PASS}"
  privateKeyEntryAlias: "${SAML_PKE_ALIAS}"
  privateKeyEntryPassword: "${SAML_PKE_PASS}"
  idpMetadataUrl: "${SAML_IDP_URL}"
  spEntityId: "${SAML_SP_ENTITY_ID}"

zuul:
  #host:
  #  socket-timeout-millis: 10000
  routes:
    ims-api:
      path: /api/ims/**
      url: http://localhost:8081/api

server:
  session:
    timeout: 800
