version: '2'
services:
    config-server:
        container_name: config-server
        image: fwsbac/configuration-service
        environment:
          CONFIG_SERVICE_REPO: "file://tmp"
        expose:
            - 8888
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network
        volumes:
            - @USER_HOME@/smarter_app/sbac-config-repo:/tmp
        logging:
            driver: json-file
    ap-ims:
        container_name: ap-ims
        image: fwsbac/ap-ims
        environment:
            CONFIG_SERVICE_ENABLED: "true"
            CONFIG_SERVICE_URL: "http://config-server:8888"
        ports:
            - 8081:8080
        networks:
            - spring-cloud-network
        links:
            - config-server
        depends_on:
            - config-server
        volumes:
            - @USER_HOME@/smarter_app:/tmp
        logging:
            driver: json-file
    ap-iat:
        container_name: ap-iat
        image: fwsbac/ap-iat
        environment:
            CONFIG_SERVICE_ENABLED: "true"
            CONFIG_SERVICE_URL: "http://config-server:8888"
            SPRING_CONFIG_LOCATION: "/tmp/security/ap-iat/ap-iat-security.yml"
        expose:
            - 8082
        ports:
            - 8082:8082
        networks:
            - spring-cloud-network
        links:
            - config-server
            - ap-ims
        depends_on:
            - config-server
            - ap-ims
        volumes:
            - @USER_HOME@/smarter_app:/tmp
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge

